language: node_js
node_js:
- node
install:
- yarn -i
script:
- npm test
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: ArC1V5kgVg0wudZZMLyP0Z0j/N+tvGPe5niLP4lYnv7/WBwOdJac0wWlFqtUp6OowFLjw6BH2yjIuC0e2wFT9YgcTqnLn7pMisdoQNtH0IsUPHs4elxLfT7ScTJj+sq9RRGxV03/qhxxL/L6DR5OlOx27V5kpMg211XURVzR4F1NlQpedAezVItKia8AzVy7h/PgXcc+r0MnA5/4+n1u1Q9zAKwHZ3t6j8ljeTGijozwTlBchRWS6qif5cClVZXP1lvotFjERxycKle6RMrOKvQpFOIigOUz+/4bw6OQ+ogNKCsn3rBxS9oX2z8w7LBBl1HASkDkKhPAsnrlK/JEvzym6bahxhbt7nGV8aTq91Ga2eZhUSD0HOLTNoNqOJZFTYBAO4FFC4kxi3jQ3M6ATeKDfYcQF44FhR0pxcePhFltXh5JcnfklbaYYcjVtTDRVqE1hTghd9G3oK0kwqBxdRmvtdyXJbzLNn9OopLwLgVAMDfPj6wTzxNG1I+ykbUc6L9ttMVDQpPg4ot6hOp7xcPEL3BjBkIlBjekSavNTtuvuiNWmAFvQy03d9LpBTYw1DYRnpZ1BJ+o2m4cgCtLvbJHztDK4zp5mPZOZfGBuZU35cBCw+ucTn7CDH5VShWfzy4S5T9TCPijzbt+DG8AeFabVotsj3wy4YMSkcWZKaM=
  on:
    tags: true
    repo: softbrix/tucepi-rotate
